AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

require:
  - rubocop-minitest

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 25

Metrics/ParameterLists:
  Max: 10
