version: 2.1

orbs:
  # I'm using a fork of the circleci/ruby orb since the upstream version's
  # `install-deps` command assumes we have a Gemfile.lock to use in the cache
  # key which we don't. There is an open PR to allow completely custom cache
  # keys which hopefully will be merged soon:
  # https://github.com/CircleCI-Public/ruby-orb/pull/46
  ruby: cstyles/ruby@dev:install-deps-custom-key

jobs:
  lint:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
          key: gems-v1-{{ checksum "boatload.gemspec" }}
      - ruby/rubocop-check
  test:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
          key: gems-v1-{{ checksum "boatload.gemspec" }}
      - run: bin/test
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
