name: lint_and_test
on: push

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - run: bundle install --jobs 4 --retry 3
      - run: bin/lint
