name: lint_and_test
on: push

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/lint

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/test
        env:
          TESTOPTS: --verbose
          MEASURE_COVERAGE: true
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
          if-no-files-found: error
